### ISSUE TITLE
Invalid config - combination not allowed

### ISSUE THREAD

**Issue by j-a-h-i-r** [banglakit/corpus-builder#11]
Running the scraper (amader_somoy, banglanews24) gives `ValueError: combination of (end_page, start_page, __class__) not allowed'
This happens because in `corpus-builder/corpus_builder/templates/spider.py` file  `__class__` gets appended to `user_configuration`. This problem can be solved by deleting this key using `del args['__class__']`

**Comment by j-a-h-i-r** [comment]
#12

**Comment by aniruddha-adhikary** [comment]
@j-a-h-i-r Thank you so much for your contribution. (y)
