### ISSUE TITLE
python3 compatibility 

### ISSUE THREAD

**Issue by msghera** [banglakit/corpus-builder#15]
I came to know that this wonderful repo only support python 2.7.x. Shouldn't be there a compatible version for python 3 ??

**Comment by aniruddha-adhikary** [comment]
@msghera Agreed. Need someone to work on it. Are you interested? 😄

**Comment by msghera** [comment]
Just did a fork, will merge with some additional feature as soon as possible.

**Comment by aniruddha-adhikary** [comment]
That's awesome @msghera Waiting eagerly.

**Comment by msghera** [comment]
Seems like the given example for bangladesh_pratidin is not working. Don't know there is any bug or the site changed something but nothing is being fetched from there.
